export const FETCH_STATUS_COUNT_REQUEST = 'AccountDashboard/FETCH_STATUS_COUNT_REQUEST';
export const FETCH_STATUS_COUNT_SUCCESS = 'AccountDashboard/FETCH_STATUS_COUNT_SUCCESS';
export const FETCH_STATUS_COUNT_FAILURE = 'AccountDashboard/FETCH_STATUS_COUNT_FAILURE';
