export const FETCH_STATUS_COUNT_REQUEST = 'ACCOUNT_DASHBOARD/FETCH_STATUS_COUNT_REQUEST';
export const FETCH_STATUS_COUNT_SUCCESS = 'ACCOUNT_DASHBOARD/FETCH_STATUS_COUNT_SUCCESS';
export const FETCH_STATUS_COUNT_FAILURE = 'ACCOUNT_DASHBOARD/FETCH_STATUS_COUNT_FAILURE';
