export const BOARD_CALLBACK = 'BOARD_CALLBACK';
export const SET_POST_SETS = 'SET_POST_SETS';
export const FETCH_POST_SETS = 'FETCH_POST_SETS';
export const DELETE_POST_SET = 'DELETE_POST_SET';
export const DELETE_POST_SET_REQUEST = 'DELETE_POST_SET_REQUEST';
export const CHANGE_POST_SET_REQUEST = 'CHANGE_POST_SET_REQUEST';
export const CHANGE_POST_SET_STATUS = 'CHANGE_POST_SET_STATUS';
