export const FETCH_SUBSCRIPTIONS = 'SETTINGS/FETCH_SUBSCRIPTIONS';
export const FETCH_SUBSCRIPTIONS_SUCCESS = 'SETTINGS/FETCH_SUBSCRIPTIONS_SUCCESS';
export const FETCH_SUBSCRIPTIONS_ERROR = 'SETTINGS/FETCH_SUBSCRIPTIONS_ERROR';
