export const FETCH_SUBSCRIPTIONS = 'Settings/FETCH_SUBSCRIPTIONS';
export const FETCH_SUBSCRIPTIONS_SUCCESS = 'Settings/FETCH_SUBSCRIPTIONS_SUCCESS';
export const FETCH_SUBSCRIPTIONS_ERROR = 'Settings/FETCH_SUBSCRIPTIONS_ERROR';
export const CANCEL_SUBSCRIPTION = 'Settings/CANCEL_SUBSCRIPTION';
export const CANCEL_SUBSCRIPTION_SUCCESS = 'Settings/CANCEL_SUBSCRIPTION_SUCCESS';
export const CANCEL_SUBSCRIPTION_ERROR = 'Settings/CANCEL_SUBSCRIPTION_ERROR';
