/**
 * Dashboard constants
 *
 */

export const SET_ACTIVE_BRAND = 'Main/SET_ACTIVE_BRAND';
export const FETCH_ACCOUNT = 'Main/FETCH_ACCOUNT';
export const IS_LOADING_ACCOUNT = 'Main/IS_LOADING_ACCOUNT';
export const FETCH_ACCOUNT_SUCCESS = 'Main/FETCH_ACCOUNT_SUCCESS';
export const FETCH_ACCOUNT_ERROR = 'Main/FETCH_ACCOUNT_ERROR';
export const TOGGLE_MENU = 'Main/TOGGLE_MENU';
export const SET_CONNECTIONS_LIST = 'SET_CONNECTIONS_LIST';
export const FETCH_CONNECTIONS = 'Main/FETCH_CONNECTIONS';
export const FETCH_CONNECTIONS_SUCCESS = 'Main/FETCH_CONNECTIONS_SUCCESS';
export const FETCH_CONNECTIONS_FAILURE = 'Main/FETCH_CONNECTIONS_FAILURE';
export const SET_CONNECTIONS = 'Main/SET_CONNECTIONS';
export const SET_PROCESSING = 'Main/SET_PROCESSING';
