export const SET_CHANNEL_FILTER = 'SET_CHANNEL_FILTER';
export const SET_CHANNEL_TYPE = 'SET_CHANNEL_TYPE';
export const SET_CONNECTIONS_LIST = 'SET_CONNECTIONS_LIST';
export const TOGGLE_ADD_CONNECTION_DIALOG = 'TOGGLE_ADD_CONNECTION_DIALOG';
