export const FETCH_PUBLIC_POST_SET_REQUEST = 'PublicPage/FETCH_PUBLIC_POST_SET_REQUEST';
export const FETCH_PUBLIC_POST_SET_SUCCESS = 'PublicPage/FETCH_PUBLIC_POST_SET_SUCCESS';
export const FETCH_PUBLIC_POST_SET_ERROR = 'PublicPage/FETCH_PUBLIC_POST_SET_ERROR';
