export const FETCH_PUBLIC_POST_SET_REQUEST = 'public/FETCH_PUBLIC_POST_SET_REQUEST';
export const FETCH_PUBLIC_POST_SET_SUCCESS = 'PUBLIC/FETCH_PUBLIC_POST_SET_SUCCESS';
export const FETCH_PUBLIC_POST_SET_ERROR = 'PUBLIC/FETCH_PUBLIC_POST_SET_ERROR';
