export const FETCH_POST_SET_REQUEST = '_COMMON/FETCH_POST_SET_REQUEST';
export const FETCH_POST_SET_SUCCESS = '_COMMON/FETCH_POST_SET_SUCCESS';
export const FETCH_POST_SET_ERROR = '_COMMON/FETCH_POST_SET_ERROR';
export const UPDATE_POST_SET_REQUEST = '_COMMON/UPDATE_POST_SET_REQUEST';
export const UPDATE_POST_SET_SUCCESS = '_COMMON/UPDATE_POST_SET_SUCCESS';
export const UPDATE_POST_SET_ERROR = '_COMMON/UPDATE_POST_SET_ERROR';
