export const POST_COMMENT_REQUEST = 'POST_COMMENT_REQUEST';
export const ADD_COMMENT = 'ADD_COMMENT';
export const FETCH_COMMENTS_REQUEST = 'FETCH_COMMENTS_REQUEST';
export const SET_COMMENTS = 'SET_COMMENTS';
