export const POST_COMMENT_REQUEST = 'POST_COMMENT_REQUEST';
export const ADD_COMMENT = 'ADD_COMMENT';
export const FETCH_COMMENTS_REQUEST = 'FETCH_COMMENTS_REQUEST';
export const SET_COMMENTS = 'SET_COMMENTS';
export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const FETCH_ACCOUNT_TAGS_REQUEST = 'FETCH_ACCOUNT_TAGS_REQUEST';
export const SET_ACCOUNT_TAGS = 'SET_ACCOUNT_TAGS';
