export const FETCH_PLAN = 'Signup/FETCH_PLAN';
export const FETCH_PLAN_SUCCESS = 'Signup/FETCH_PLAN_SUCCESS';
export const FETCH_PLAN_ERROR = 'Signup/FETCH_PLAN_ERROR';
export const RESEND_ACTIVATION_EMAIL = 'Signup/RESEND_ACTIVATION_EMAIL';
export const RESEND_ACTIVATION_EMAIL_SUCCESS = 'Signup/RESEND_ACTIVATION_EMAIL_SUCCESS';
