/**
 * Global constants
 */
export const SET_AUTH = 'app/app/SET_AUTH';
export const SENDING_REQUEST = 'app/SENDING_REQUEST';
export const LOGIN_REQUEST = 'app/LOGIN_REQUEST';
export const REGISTER_REQUEST = 'app/REGISTER_REQUEST';
export const UPDATE_REQUEST = 'app/UPDATE_REQUEST';
export const LOGOUT = 'app/LOGOUT';
export const REQUEST_ERROR = 'app/REQUEST_ERROR';
export const CLEAR_ERROR = 'app/CLEAR_ERROR';
export const SET_USER = 'app/SET_USER';
export const GET_USER = 'app/GET_USER';
export const CHECK_USER_OBJECT = 'app/CHECK_USER_OBJECT';
export const CLEAR_USER = 'app/CLEAR_USER';
export const CHECK_CURRENT_ACCOUNT = 'app/CHECK_CURRENT_ACCOUNT';
export const CREATE_PAYMENT_SOURCE = 'app/CREATE_PAYMENT_SOURCE';
export const CREATE_PAYMENT_SOURCE_SUCCESS = 'app/CREATE_PAYMENT_SOURCE_SUCCESS';
export const CREATE_PAYMENT_SOURCE_ERROR = 'app/CREATE_PAYMENT_SOURCE_ERROR';
export const APPLY_COUPON = 'app/APPLY_COUPON';
export const APPLY_COUPON_SUCCESS = 'app/APPLY_COUPON_SUCCESS';
export const APPLY_COUPON_ERROR = 'app/APPLY_COUPON_ERROR';
export const POST_SUBSCRIPTION = 'app/POST_SUBSCRIPTION';
export const POST_SUBSCRIPTION_SUCCESS = 'app/POST_SUBSCRIPTION_SUCCESS';
export const POST_SUBSCRIPTION_ERROR = 'app/POST_SUBSCRIPTION_ERROR';
export const FETCH_CURRENT_PLAN = 'app/FETCH_CURRENT_PLAN';
export const FETCH_CURRENT_PLAN_SUCCESS = 'app/FETCH_CURRENT_PLAN_SUCCESS';
export const FETCH_CURRENT_PLAN_ERROR = 'app/FETCH_CURRENT_PLAN_ERROR';
export const FETCH_PAYMENT_SOURCES = 'app/FETCH_PAYMENT_SOURCES';
export const FETCH_PAYMENT_SOURCES_SUCCESS = 'app/FETCH_PAYMENT_SOURCES_SUCCESS';
export const FETCH_PAYMENT_SOURCES_ERROR = 'app/FETCH_PAYMENT_SOURCES_ERROR';
export const FETCH_PAYMENT_HISTORY = 'app/FETCH_PAYMENT_HISTORY';
export const FETCH_PAYMENT_HISTORY_SUCCESS = 'app/FETCH_PAYMENT_HISTORY_SUCCESS';
export const FETCH_PAYMENT_HISTORY_ERROR = 'app/FETCH_PAYMENT_HISTORY_ERROR';
export const FETCH_GROUP_USERS = 'app/FETCH_GROUP_USERS';
export const FETCH_GROUP_USERS_SUCCESS = 'app/FETCH_GROUP_USERS_SUCCESS';
export const FETCH_GROUP_USERS_ERROR = 'app/FETCH_GROUP_USERS_ERROR';
export const INVITE_EMAIL_TO_GROUP = 'app/INVITE_EMAIL_TO_GROUP';
export const INVITE_EMAIL_TO_GROUP_SUCCESS = 'app/INVITE_EMAIL_TO_GROUP_SUCCESS';
export const INVITE_EMAIL_TO_GROUP_ERROR = 'app/INVITE_EMAIL_TO_GROUP_ERROR';
export const ADD_USER_TO_GROUP = 'app/ADD_USER_TO_GROUP';
export const ADD_USER_TO_GROUP_SUCCESS = 'app/ADD_USER_TO_GROUP_SUCCESS';
export const ADD_USER_TO_GROUP_ERROR = 'app/ADD_USER_TO_GROUP_ERROR';
export const REMOVE_USER_FROM_GROUP = 'app/REMOVE_USER_FROM_GROUP';
export const REMOVE_USER_FROM_GROUP_SUCCESS = 'app/REMOVE_USER_FROM_GROUP_SUCCESS';
export const REMOVE_USER_FROM_GROUP_ERROR = 'app/REMOVE_USER_FROM_GROUP_ERROR';
export const BOARD_CALLBACK = 'app/BOARD_CALLBACK';

/* Post sets */
export const FETCH_POST_SETS_REQUEST = 'app/FETCH_POST_SETS_REQUEST';
export const FETCH_POST_SETS_SUCCESS = 'app/FETCH_POST_SETS_SUCCESS';
export const FETCH_POST_SETS_FAILURE = 'app/FETCH_POST_SETS_FAILURE';
export const FETCH_POST_SETS_BY_ST_REQUEST = 'app/FETCH_POST_SETS_BY_ST_REQUEST';
export const FETCH_POST_SETS_BY_ST_SUCCESS = 'app/FETCH_POST_SETS_BY_ST_SUCCESS';
export const FETCH_POST_SETS_BY_ST_FAILURE = 'app/FETCH_POST_SETS_BY_ST_FAILURE';
export const FETCH_STREAM_POST_SETS_REQUEST = 'app/FETCH_STREAM_POST_SETS_REQUEST';
export const FETCH_STREAM_POST_SETS_SUCCESS = 'app/FETCH_STREAM_POST_SETS_SUCCESS';
export const FETCH_STREAM_POST_SETS_FAILURE = 'app/FETCH_STREAM_POST_SETS_FAILURE';

/* Post set */
export const FETCH_POST_SET_REQUEST = 'app/FETCH_POST_SET_REQUEST';
export const FETCH_POST_SET_SUCCESS = 'app/FETCH_POST_SET_SUCCESS';
export const FETCH_POST_SET_FAILURE = 'app/FETCH_POST_SET_FAILURE';
export const CREATE_POST_SET_REQUEST = 'app/CREATE_POST_SET_REQUEST';
export const CREATE_POST_SET_SUCCESS = 'app/CREATE_POST_SET_SUCCESS';
export const CREATE_POST_SET_FAILURE = 'app/CREATE_POST_SET_FAILURE';
export const UPDATE_POST_SET_REQUEST = 'app/UPDATE_POST_SET_REQUEST';
export const UPDATE_POST_SET_SUCCESS = 'app/UPDATE_POST_SET_SUCCESS';
export const UPDATE_POST_SET_FAILURE = 'app/UPDATE_POST_SET_FAILURE';
export const DELETE_POST_SET_REQUEST = 'app/DELETE_POST_SET_REQUEST';
export const DELETE_POST_SET_SUCCESS = 'app/DELETE_POST_SET_SUCCESS';
export const DELETE_POST_SET_FAILURE = 'app/DELETE_POST_SET_SUCCESS';
export const CHANGE_POST_SET_STATUS_REQUEST = 'app/CHANGE_POST_SET_STATUS_REQUEST';
export const CHANGE_POST_SET_STATUS_SUCCESS = 'app/CHANGE_POST_SET_STATUS_SUCCESS';
export const CHANGE_POST_SET_SORT_ORDER_REQUEST = 'app/CHANGE_POST_SET_SORT_ORDER_REQUEST';
export const CHANGE_POST_SET_SORT_ORDER_SUCCESS = 'app/CHANGE_POST_SET_SORT_ORDER_SUCCESS';
export const SAVE_POST_SET_SORT_ORDER_REQUEST = 'app/SAVE_POST_SET_SORT_ORDER_REQUEST';
export const SAVE_POST_SET_SORT_ORDER_SUCCESS = 'app/SAVE_POST_SET_SORT_ORDER_SUCCESS';
export const REPLICATE_POST_SET_REQUEST = 'app/REPLICATE_POST_SET_REQUEST';
export const REPLICATE_POST_SET_SUCCESS = 'app/REPLICATE_POST_SET_SUCCESS';
export const REPLICATE_POST_SET_FAILURE = 'app/REPLICATE_POST_SET_FAILURE';

/* Posts */
export const FETCH_POSTS_REQUEST = 'app/FETCH_POSTS_REQUEST';
export const FETCH_POSTS_SUCCESS = 'app/FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAILURE = 'app/FETCH_POSTS_FAILURE';
/* Post */
export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_FAILURE = 'CREATE_POST_FAILURE';
export const UPDATE_POST_REQUEST = 'app/UPDATE_POST_REQUEST';
export const UPDATE_POST_SUCCESS = 'app/UPDATE_POST_SUCCESS';
export const UPDATE_POST_FAILURE = 'app/UPDATE_POST_FAILURE';
export const CREATE_BUNCH_POSTS_REQUEST = 'app/CREATE_BUNCH_POSTS_REQUEST';
export const CREATE_BUNCH_POSTS_SUCCESS = 'app/CREATE_BUNCH_POSTS_SUCCESS';
export const CREATE_BUNCH_POSTS_FAILURE = 'app/CREATE_BUNCH_POSTS_FAILURE';
export const ADD_POST_TO_POST_SET = 'app/ADD_POST_TO_POSTSET';
export const UPDATE_BUNCH_POSTS_REQUEST = 'app/UPDATE_BUNCH_POSTS_REQUEST';
export const UPDATE_BUNCH_POSTS_SUCCESS = 'app/UPDATE_BUNCH_POSTS_SUCCESS';
export const UPDATE_BUNCH_POSTS_FAILURE = 'app/UPDATE_BUNCH_POSTS_FAILURE';
export const SET_POST = 'app/SET_POST';
export const CLEAR_POST = 'app/CLEAR_POST';

/* Media items */
export const FETCH_MEDIA_ITEMS_REQUEST = 'app/FETCH_MEDIA_ITEMS_REQUEST';
export const FETCH_MEDIA_ITEMS_SUCCESS = 'app/FETCH_MEDIA_ITEMS_SUCCESS';
export const FETCH_MEDIA_ITEMS_FAILURE = 'app/FETCH_MEDIA_ITEMS_FAILURE';
export const CREATE_MEDIA_ITEM = 'app/CREATE_MEDIA_ITEM';
export const CREATE_MEDIA_ITEM_SUCCESS = 'app/CREATE_MEDIA_ITEM_SUCCESS';
export const CREATE_MEDIA_ITEM_ERROR = 'app/CREATE_MEDIA_ITEM_ERROR';
export const UPDATE_MEDIA_ITEM = 'app/UPDATE_MEDIA_ITEM';
export const UPDATE_MEDIA_ITEM_SUCCESS = 'app/UPDATE_MEDIA_ITEM_SUCCESS';
export const VIDEO_PROCESSING = 'app/VIDEO_PROCESSING';
export const VIDEO_PROCESSING_DONE = 'app/VIDEO_PROCESSING_DONE';
export const REMOVE_MEDIA_ITEM = 'app/REMOVE_MEDIA_ITEM';
export const SET_MEDIA_ITEM = 'app/SET_MEDIA_ITEM';
