/**
 * Global constants
 *
 */

export const SET_AUTH = 'SET_AUTH';
export const SENDING_REQUEST = 'SENDING_REQUEST';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const UPDATE_REQUEST = 'UPDATE_REQUEST';
export const LOGOUT = 'LOGOUT';
export const REQUEST_ERROR = 'REQUEST_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const SET_USER = 'SET_USER';
export const GET_USER = 'GET_USER';
export const CHECK_USER_OBJECT = 'CHECK_USER_OBJECT';
export const CLEAR_USER = 'CLEAR_USER';
export const CHECK_CURRENT_ACCOUNT = 'CHECK_CURRENT_ACCOUNT';
export const CREATE_PAYMENT_SOURCE = 'CREATE_PAYMENT_SOURCE';
export const CREATE_PAYMENT_SOURCE_SUCCESS = 'CREATE_PAYMENT_SOURCE_SUCCESS';
export const CREATE_PAYMENT_SOURCE_ERROR = 'CREATE_PAYMENT_SOURCE_ERROR';
export const APPLY_COUPON = 'APPLY_COUPON';
export const APPLY_COUPON_SUCCESS = 'APPLY_COUPON_SUCCESS';
export const APPLY_COUPON_ERROR = 'APPLY_COUPON_ERROR';
export const POST_SUBSCRIPTION = 'POST_SUBSCRIPTION';
export const POST_SUBSCRIPTION_SUCCESS = 'POST_SUBSCRIPTION_SUCCESS';
export const POST_SUBSCRIPTION_ERROR = 'POST_SUBSCRIPTION_ERROR';
export const FETCH_CURRENT_PLAN = 'FETCH_CURRENT_PLAN';
export const FETCH_CURRENT_PLAN_SUCCESS = 'FETCH_CURRENT_PLAN_SUCCESS';
export const FETCH_CURRENT_PLAN_ERROR = 'FETCH_CURRENT_PLAN_ERROR';
