/**
 * Global constants
 *
 */

export const SET_AUTH = 'SET_AUTH';
export const SENDING_REQUEST = 'SENDING_REQUEST';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const UPDATE_REQUEST = 'UPDATE_REQUEST';
export const LOGOUT = 'LOGOUT';
export const REQUEST_ERROR = 'REQUEST_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const SET_USER = 'SET_USER';
export const GET_USER = 'GET_USER';
export const CHECK_USER_OBJECT = 'CHECK_USER_OBJECT';
export const CLEAR_USER = 'CLEAR_USER';
export const CHECK_CURRENT_ACCOUNT = 'CHECK_CURRENT_ACCOUNT';
export const CREATE_PAYMENT_SOURCE = 'CREATE_PAYMENT_SOURCE';
export const CREATE_PAYMENT_SOURCE_SUCCESS = 'CREATE_PAYMENT_SOURCE_SUCCESS';
export const CREATE_PAYMENT_SOURCE_ERROR = 'CREATE_PAYMENT_SOURCE_ERROR';
