export const SET_BRAND_FILTER = 'SET_BRAND_FILTER';
export const CREATE_BRAND = 'CREATE_BRAND';
export const DELETE_BRAND = 'DELETE_BRAND';
export const SET_NEW_BRAND = 'SET_NEW_BRAND';
export const SET_DELETE_BRAND = 'SET_DELETE_BRAND';
