export const SET_BRAND_FILTER = 'SET_BRAND_FILTER';
export const SET_CONNECTIONS_LIST = 'SET_CONNECTIONS_LIST';
export const TOGGLE_ADD_CONNECTION_DIALOG = 'TOGGLE_ADD_CONNECTION_DIALOG';
export const CONNECTION_CALLBACK = 'CONNECTION_CALLBACK';
